config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :attendees, only: [:destroy]
  devise_for :users
  authenticated :user do
    root to: 'events#index', as: :authenticated_root
  end
  unauthenticated do
    root to: 'visitors#index', as: :unauthenticated_root
  end
end

app/models/attendee.rb
class Attendee < ActiveRecord::Base
  validates :name, presence: true
  validates :email, presence: true
  belongs_to :event
end

app/models/event.rb
class Event < ActiveRecord::Base
  validates :title, presence: true
  validates :user, presence: true
  has_many :attendees
  belongs_to :user

  accepts_nested_attributes_for :attendees, reject_if: :all_blank, allow_destroy: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :events
end

app/controllers/application_controller.rb
# Main controller for app
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/attendees_controller.rb
# Controller for attendees ( mostly to destroy )
class AttendeesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_attendee

  def destroy
    @attendee.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Attendee was removed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_attendee
    @attendee = Attendee.find(params[:id])
  end
end

app/controllers/events_controller.rb
# Controller for events ( management of events )
class EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = current_user.events.order('created_at desc').page(params[:page])
  end

  def show
  end

  def new
    @event = Event.new
  end

  def edit
  end

  def create
    @event = Event.new(event_params)
    respond_to do |format|
      if @event.save
        format.html do
          redirect_to @event, notice: 'Event was successfully created.'
        end
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html do
          redirect_to @event, notice: 'Event was successfully updated.'
        end
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @event.destroy
    respond_to do |format|
      format.html do
        redirect_to events_url, notice: 'Event was successfully destroyed.'
      end
    end
  end

  private

  def set_event
    @event = current_user.events.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :user_id, attendees_attributes: [:name, :event_id, :email, :id, :_destroy])
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
# Main Application Helper
module ApplicationHelper
end

app/views/attendees/_attendee.html.haml
= attendee.name
= attendee.email
= link_to "Remove attendee", attendee_path(attendee), method: :delete
%br

app/views/events/_attendee_fields.html.haml
.nested-fields
  .form-group
    = f.label :name, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :email, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :email, class: 'form-control'
  = link_to_remove_association "Remove Attendee", f

app/views/events/_form.html.haml
= form_for event, html: { class: "form-horizontal", role: "form" } do |f|
  = f.hidden_field :user_id, value: current_user.id
  -if event.errors.any?
    .alert.alert-danger.alert-dismissable{role: "alert"}
      %button.close{type: "button", data: {dismiss: "alert"} }
        %span{aria: {hidden: "true"} } &times;
        %span.sr-only Close
      %h4= "#{pluralize(event.errors.count, "error")} prohibited this event from being saved:"

      %ul
        - event.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :title, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :title, class: 'form-control'
  %hr
  .col-lg-10.col-lg-offset-2
    %h3 Attendees
    #attendees
      = f.fields_for :attendees do |attendee|
        = render 'attendee_fields', f: attendee
      .links
        = link_to_add_association 'Add an attendee', f, :attendees, class: 'btn btn-default'
  %br
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: 'btn btn-primary pull-right'

app/views/events/edit.html.haml
.page-header
  = link_to events_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @event, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing event

= render 'form', event: @event

app/views/events/index.html.haml
.page-header
  = link_to new_event_path, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
    New Event
  %h1 Listing events

.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th Title
        %th
        %th
        %th

    %tbody
      - @events.each do |event|
        %tr
          %td= event.title
          %td= link_to 'Show', event
          %td= link_to 'Edit', edit_event_path(event)
          %td= link_to 'Destroy', event, data: { confirm: 'Are you sure?' }, method: :delete
      - if @events.empty?
        %tr
          %td= "No Events"
          %td
          %td
          %td

= paginate @events, :theme => 'twitter-bootstrap-3'

app/views/events/new.html.haml
.page-header
  = link_to events_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 New event

= render 'form', event: @event

app/views/events/show.html.haml
.page-header
  = link_to events_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to edit_event_path(@event), class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Edit
  %h1 Show event

%dl.dl-horizontal
  %dt Title:
  %dd= @event.title
%dl.dl-horizontal
  %dt Attendees
  %dd
    = render @event.attendees
    = "No Attendees" if @event.attendees.empty?

app/views/layouts/_navigation.html.haml
- if user_signed_in?
  %li= link_to "Edit Account", edit_user_registration_path
  %li= link_to "Sign out", destroy_user_session_path, method: :delete
- else
  %li= link_to 'Sign in', new_user_session_path
  %li= link_to 'Sign up', new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{charset: "utf-8"}
    %meta{content: "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}
    %meta{content: "", name: "description"}
    %meta{content: "", name: "author"}
    %title Evtest

    / HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
      = javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js"

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-inverse.navbar-fixed-top{role: "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{type: "button", data: {toggle: "collapse", target: "#navbar"}, aria: {expanded: "false", controls: "navbar"} }
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to 'Home', "/", class: 'navbar-brand'
        #navbar.collapse.navbar-collapse
          %ul.nav.navbar-nav
            = render 'layouts/navigation'
    .container#content
      - flash.each do |name, msg|
        = content_tag :div, class: "alert alert-#{name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do
          %button.close{type: "button", data: {dismiss: "alert"} }
            %span{aria: {hidden: "true"} } &times;
            %span.sr-only Close
          = msg
      = yield

app/views/visitors/index.html.haml
.jumbotron
  .container
    %h1 Welcome to Evtest
    %p You can track you event attendees by creating an account or signing in above.
    %p
      %a.btn.btn-primary.btn-lg{:href => new_user_registration_path, :role => "button"} Sign up